# Plugins
gems:
  - 'jekyll-paginate'
  - 'jekyll-gist'
  - 'jekyll-github-metadata'

# Dependencies
highlighter: rouge

# Setup
title: EZC
tagline: Multiprecision Programming Language
description: "When 32 bits isn't enough, use EZC"
url: https://github.com/ChemicalDevelopment/ezc
baseurl: /

author:
  name: 'Cade Brown'
  url: cade.site

paginate: 5

release: 1.0.0

repository: ChemicalDevelopment/ezc
