[package]
name = "ezc-lsp"
description = "Language server for the ezc language"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "ezc-lsp"
path = "src/main.rs"

[dependencies]
ezc.workspace = true
tower-lsp.workspace = true
tokio.workspace = true
serde_json.workspace = true
