<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>text.ezc</string>

        <key>fileTypes</key>
        <array>
            <string>ezc</string>
        </array>

        <key>name</key>
        <string>EZC File</string>

        <key>patterns</key>
        <array>

		<dict>
			<key>match</key>
			<string>.*;</string>
			<key>name</key>
			<string>constant.string</string>
		</dict>

		<!--  Comments, # is single line, and ### is multiline (with ### ending the comment)  -->

		<dict>
			<key>patterns</key>
			<array>

				<dict>
					<key>begin</key>
					<string>###</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.c</string>
						</dict>
					</dict>
					<key>end</key>
					<string>###</string>
					<key>name</key>
					<string>comment.block.c</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.ezc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.ezc</string>
					
				</dict>
			</array>
		</dict>


		<!-- User defined function declaration (args) Overrules default functions -->

		<dict>
			<key>match</key>
			<string>\[([a-zA-Z_0-9]+)\]((?:\ [a-zA-Z0-9_])+)</string>
			<key>name</key>
			<string>support.type.sys-types.args</string>
		</dict>

		<!-- User defined function (call). Overrules default functions -->

		<dict>
			<key>match</key>
			<string>(@(\{)?[a-zA-Z_0-9]+)(.*\})?</string>
			<key>name</key>
			<string>support.type.sys-types.functions</string>
		</dict>


		<!-- Numerical constant (or built in variable, such as ONE, or TWO) -->

		<dict>
			<key>match</key>
			<string>(\+|\-)?[0-9\.]+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>        


		<!-- All operators, and $ for indexing commandline args -->

		<dict>
			<key>match</key>
			<string>(\~|\^|choose|\!|\*|\/|\÷|\%|\+|\-|\~|\?)</string>
			<key>name</key>
            <string>support.function.builtin.call.ezc</string>
		</dict>   


		<!-- Comparing, used in if block -->

		<dict>
			<key>match</key>
			<string>(<|>|=<|==|>=|!=|\$)</string>
			<key>name</key>
			<string>support.keyword.compare</string>
		</dict>  


		<!-- Flow blocks, like for, if, and : for splitting lines -->

		<dict>
			<key>match</key>
			<string>(rof|__base|for|label|goto|if|fi|set|prec|intvar|var|:|echo|\"\")</string>
			<key>name</key>
			<string>keyword.control.ezc</string>
		</dict>

		<!-- Math functions -->

		<dict>
			<key>match</key>
			<string>(svar|binomcoef|binompdf|binomcdf|binomcdf_1|normalpdf|normalcdf|erf|free|prompt|if|else|file|fi|for|rof|prec|add|sub|mul|div|pow|mod|\"|mpz|var|rawvar|intvar|rawintvar|set|sqrt|\√|cbrt|min|max|near|trunc|rand|fact|echo|printf|hypot|exp|log|agm|gamma|factorial|zeta|\ζ|pi|deg|rad|sin|cos|tan|asin|acos|atan|csc|sec|cot|acsc|asec|acot|sinh|cosh|tanh|asinh|acosh|atanh|csch|sech|coth|acsch|asech|acoth)</string>
			<key>name</key>
			<string>support.function.builtin.call.ezc</string>
		</dict>  

        </array>
        <key>uuid</key>
        <string>FF0550E0-3A29-11E3-AA6E-0800200C9A77</string>
    </dict>
</plist>