<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>text.ezc</string>

        <key>fileTypes</key>
        <array>
            <string>ezc</string>
        </array>

        <key>name</key>
        <string>EZC File</string>

        <key>patterns</key>
        <array>
		<dict>
			<key>patterns</key>
			<array>

				<dict>
					<key>begin</key>
					<string>###</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.c</string>
						</dict>
					</dict>
					<key>end</key>
					<string>###</string>
					<key>name</key>
					<string>comment.block.c</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.ezc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.ezc</string>
					
				</dict>
			</array>
		</dict>


		<dict>
			<key>match</key>
			<string>(set|echo|prec|var)(?![_a-zA-Z])</string>
			<key>name</key>
			<string>keyword.control.ezc</string>
		</dict>

            <dict>
                <key>match</key>
                <string>\b(?i:(goto|if|for|fi|rof|label))\b</string>
                <key>name</key>

                <string>constant.other.functions</string>
            </dict>          

		<dict>
			<key>match</key>
			<string>(div|log|cos|exp|acos|atan|max|mul|sin|add|min|asin|logb|sqrt|tan|pow|sub)(?![_a-zA-Z])</string>
			<key>name</key>
			<string>support.type.sys-types.functions</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(prec|var|echo|\+|\-|\*|\/|\^|\*\*|_|\%)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>   


		<dict>
			<key>match</key>
			<string>("[a-zA-Z0-9]+"|(?<=echo )([a-zA-Z0-9]+))</string>
			<key>name</key>
			<string>constant.string</string>
		</dict>
            <dict>
                <key>match</key>
                <string>(=|<|>|=<|==|>=|!=|\$)</string>
                <key>name</key>
                <string>support.keyword.compare</string>
            </dict>        

            <dict>
                <key>match</key>
                <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
                <key>name</key>
                <string>support.function.builtin.call.ezc</string>
            </dict>        

        </array>
        <key>uuid</key>
        <string>FF0550E0-3A29-11E3-AA6E-0800200C9A77</string>
    </dict>
</plist>